// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wozghfettijeibwhycan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvemdoZmV0dGlqZWlid2h5Y2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Mjg3NzUsImV4cCI6MjA2OTEwNDc3NX0.62wPmF6ozNveb1Nu4SEvNoN4h1iyFbR58sPZTmGel28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});